### ISSUE TITLE
upcloud error

### ISSUE THREAD

**Issue by off-whikoma** [samueljklee/httpProxyCreator#1]
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\ProxyMaker-master\upCloud\run.py", line 536, in <module>
    ACCOUNT().status()
  File "C:\Users\admin\Desktop\ProxyMaker-master\upCloud\run.py", line 480, in status
    self.getUUID(endpoint)
  File "C:\Users\admin\Desktop\ProxyMaker-master\upCloud\run.py", line 174, in getUUID
    uuidFP.write(bytes(server[i]["uuid"]+"\n", encoding="utf-8"))
TypeError: str() takes at most 1 argument (2 given)

**Comment by mindshatter** [comment]
Nevermind, found the issue.

**Comment by samueljklee** [comment]
Which python version are you using?

**Comment by samueljklee** [comment]
I believe you're using Python 2. Python 2 's `str()` is a byte string. This is written in Python 3 which has a different method of encoding strings to bytes. Use Python 3 to fix it.
